var searchData=
[
  ['satellite_20status_20c_0',['(0x81,0x20) Satellite Status [C]',['../group__c__gnss__satellite__status.html',1,'']]],
  ['satellite_20status_20cpp_1',['(0x81,0x20) Satellite Status [CPP]',['../group__cpp__gnss__satellite__status.html',1,'']]],
  ['sbas_20correction_20c_2',['(0x81,0x13) Sbas Correction [C]',['../group__c__gnss__sbas__correction.html',1,'']]],
  ['sbas_20correction_20cpp_3',['(0x81,0x13) Sbas Correction [CPP]',['../group__cpp__gnss__sbas__correction.html',1,'']]],
  ['sbas_20info_20c_4',['(0x81,0x12) Sbas Info [C]',['../group__c__gnss__sbas__info.html',1,'']]],
  ['sbas_20info_20cpp_5',['(0x81,0x12) Sbas Info [CPP]',['../group__cpp__gnss__sbas__info.html',1,'']]],
  ['sbas_20settings_20c_6',['(0x0C,0x22) Gnss Sbas Settings [C]',['../group__c__3dm__gnss__sbas__settings.html',1,'']]],
  ['sbas_20settings_20cpp_7',['(0x0C,0x22) Gnss Sbas Settings [CPP]',['../group__cpp__3dm__gnss__sbas__settings.html',1,'']]],
  ['scale_20factor_20c_8',['scale factor c',['../group__c__filter__gyro__scale__factor.html',1,'(0x82,0x16) Gyro Scale Factor [C]'],['../group__c__filter__accel__scale__factor.html',1,'(0x82,0x17) Accel Scale Factor [C]']]],
  ['scale_20factor_20cpp_9',['scale factor cpp',['../group__cpp__filter__gyro__scale__factor.html',1,'(0x82,0x16) Gyro Scale Factor [CPP]'],['../group__cpp__filter__accel__scale__factor.html',1,'(0x82,0x17) Accel Scale Factor [CPP]']]],
  ['scale_20factor_20error_20c_10',['(0x82,0x47) Odometer Scale Factor Error [C]',['../group__c__filter__odometer__scale__factor__error.html',1,'']]],
  ['scale_20factor_20error_20cpp_11',['(0x82,0x47) Odometer Scale Factor Error [CPP]',['../group__cpp__filter__odometer__scale__factor__error.html',1,'']]],
  ['scale_20factor_20error_20uncertainty_20c_12',['(0x82,0x48) Odometer Scale Factor Error Uncertainty [C]',['../group__c__filter__odometer__scale__factor__error__uncertainty.html',1,'']]],
  ['scale_20factor_20error_20uncertainty_20cpp_13',['(0x82,0x48) Odometer Scale Factor Error Uncertainty [CPP]',['../group__cpp__filter__odometer__scale__factor__error__uncertainty.html',1,'']]],
  ['scale_20factor_20uncertainty_20c_14',['scale factor uncertainty c',['../group__c__filter__gyro__scale__factor__uncertainty.html',1,'(0x82,0x18) Gyro Scale Factor Uncertainty [C]'],['../group__c__filter__accel__scale__factor__uncertainty.html',1,'(0x82,0x19) Accel Scale Factor Uncertainty [C]']]],
  ['scale_20factor_20uncertainty_20cpp_15',['scale factor uncertainty cpp',['../group__cpp__filter__gyro__scale__factor__uncertainty.html',1,'(0x82,0x18) Gyro Scale Factor Uncertainty [CPP]'],['../group__cpp__filter__accel__scale__factor__uncertainty.html',1,'(0x82,0x19) Accel Scale Factor Uncertainty [CPP]']]],
  ['scaled_20accel_20c_16',['(0x80,0x04) Scaled Accel [C]',['../group__c__sensor__scaled__accel.html',1,'']]],
  ['scaled_20accel_20cpp_17',['(0x80,0x04) Scaled Accel [CPP]',['../group__cpp__sensor__scaled__accel.html',1,'']]],
  ['scaled_20gyro_20c_18',['(0x80,0x05) Scaled Gyro [C]',['../group__c__sensor__scaled__gyro.html',1,'']]],
  ['scaled_20gyro_20cpp_19',['(0x80,0x05) Scaled Gyro [CPP]',['../group__cpp__sensor__scaled__gyro.html',1,'']]],
  ['scaled_20mag_20c_20',['(0x80,0x06) Scaled Mag [C]',['../group__c__sensor__scaled__mag.html',1,'']]],
  ['scaled_20mag_20cpp_21',['(0x80,0x06) Scaled Mag [CPP]',['../group__cpp__sensor__scaled__mag.html',1,'']]],
  ['scaled_20pressure_20c_22',['(0x80,0x17) Scaled Pressure [C]',['../group__c__sensor__scaled__pressure.html',1,'']]],
  ['scaled_20pressure_20cpp_23',['(0x80,0x17) Scaled Pressure [CPP]',['../group__cpp__sensor__scaled__pressure.html',1,'']]],
  ['sculling_20enable_20c_24',['(0x0C,0x3E) Coning Sculling Enable [C]',['../group__c__3dm__coning__sculling__enable.html',1,'']]],
  ['sculling_20enable_20cpp_25',['(0x0C,0x3E) Coning Sculling Enable [CPP]',['../group__cpp__3dm__coning__sculling__enable.html',1,'']]],
  ['seconds_20c_26',['(0x81,0x11) Gps Leap Seconds [C]',['../group__c__gnss__gps__leap__seconds.html',1,'']]],
  ['seconds_20cpp_27',['(0x81,0x11) Gps Leap Seconds [CPP]',['../group__cpp__gnss__gps__leap__seconds.html',1,'']]],
  ['sensor_202_20vehicle_20transform_20dcm_20c_28',['(0x0C,0x33) Sensor 2 Vehicle Transform Dcm [C]',['../group__c__3dm__sensor__2__vehicle__transform__dcm.html',1,'']]],
  ['sensor_202_20vehicle_20transform_20dcm_20cpp_29',['(0x0C,0x33) Sensor 2 Vehicle Transform Dcm [CPP]',['../group__cpp__3dm__sensor__2__vehicle__transform__dcm.html',1,'']]],
  ['sensor_202_20vehicle_20transform_20euler_20c_30',['(0x0C,0x31) Sensor 2 Vehicle Transform Euler [C]',['../group__c__3dm__sensor__2__vehicle__transform__euler.html',1,'']]],
  ['sensor_202_20vehicle_20transform_20euler_20cpp_31',['(0x0C,0x31) Sensor 2 Vehicle Transform Euler [CPP]',['../group__cpp__3dm__sensor__2__vehicle__transform__euler.html',1,'']]],
  ['sensor_202_20vehicle_20transform_20quaternion_20c_32',['(0x0C,0x32) Sensor 2 Vehicle Transform Quaternion [C]',['../group__c__3dm__sensor__2__vehicle__transform__quaternion.html',1,'']]],
  ['sensor_202_20vehicle_20transform_20quaternion_20cpp_33',['(0x0C,0x32) Sensor 2 Vehicle Transform Quaternion [CPP]',['../group__cpp__3dm__sensor__2__vehicle__transform__quaternion.html',1,'']]],
  ['sensor_20data_20c_34',['Sensor Data [C]',['../group__sensor__data__c.html',1,'']]],
  ['sensor_20data_20cpp_35',['Sensor Data [CPP]',['../group__sensor__data__cpp.html',1,'']]],
  ['sensor_20range_20c_36',['(0x0C,0x52) Sensor Range [C]',['../group__c__3dm__sensor__range.html',1,'']]],
  ['sensor_20range_20cpp_37',['(0x0C,0x52) Sensor Range [CPP]',['../group__cpp__3dm__sensor__range.html',1,'']]],
  ['sensor_20ranges_20c_38',['(0x0C,0x53) Calibrated Sensor Ranges [C]',['../group__c__3dm__calibrated__sensor__ranges.html',1,'']]],
  ['sensor_20ranges_20cpp_39',['(0x0C,0x53) Calibrated Sensor Ranges [CPP]',['../group__cpp__3dm__calibrated__sensor__ranges.html',1,'']]],
  ['sensor_20to_20vehicle_20offset_20c_40',['(0x0D,0x12) Sensor To Vehicle Offset [C]',['../group__c__filter__sensor__to__vehicle__offset.html',1,'']]],
  ['sensor_20to_20vehicle_20offset_20cpp_41',['(0x0D,0x12) Sensor To Vehicle Offset [CPP]',['../group__cpp__filter__sensor__to__vehicle__offset.html',1,'']]],
  ['sensor_20to_20vehicle_20rotation_20dcm_20c_42',['(0x0D,0x4E) Sensor To Vehicle Rotation Dcm [C]',['../group__c__filter__sensor__to__vehicle__rotation__dcm.html',1,'']]],
  ['sensor_20to_20vehicle_20rotation_20dcm_20cpp_43',['(0x0D,0x4E) Sensor To Vehicle Rotation Dcm [CPP]',['../group__cpp__filter__sensor__to__vehicle__rotation__dcm.html',1,'']]],
  ['sensor_20to_20vehicle_20rotation_20euler_20c_44',['(0x0D,0x11) Sensor To Vehicle Rotation Euler [C]',['../group__c__filter__sensor__to__vehicle__rotation__euler.html',1,'']]],
  ['sensor_20to_20vehicle_20rotation_20euler_20cpp_45',['(0x0D,0x11) Sensor To Vehicle Rotation Euler [CPP]',['../group__cpp__filter__sensor__to__vehicle__rotation__euler.html',1,'']]],
  ['sensor_20to_20vehicle_20rotation_20quaternion_20c_46',['(0x0D,0x4F) Sensor To Vehicle Rotation Quaternion [C]',['../group__c__filter__sensor__to__vehicle__rotation__quaternion.html',1,'']]],
  ['sensor_20to_20vehicle_20rotation_20quaternion_20cpp_47',['(0x0D,0x4F) Sensor To Vehicle Rotation Quaternion [CPP]',['../group__cpp__filter__sensor__to__vehicle__rotation__quaternion.html',1,'']]],
  ['serial_20port_48',['Serial Port',['../group__microstrain__serial.html',1,'']]],
  ['serialization_49',['MicroStrain Serialization',['../group__microstrain__serialization.html',1,'']]],
  ['serialization_20c_50',['MicroStrain Serialization [C]',['../group__microstrain__serialization__c.html',1,'']]],
  ['serialization_20cpp_51',['MicroStrain Serialization [CPP]',['../group__microstrain__serialization__cpp.html',1,'']]],
  ['serializers_20functions_20for_20serializing_20a_20mip_20packet_52',['Serializers - Functions for serializing a MIP packet.',['../group___serialization.html',1,'']]],
  ['serializing_20a_20mip_20packet_53',['Serializers - Functions for serializing a MIP packet.',['../group___serialization.html',1,'']]],
  ['service_20status_20c_54',['(0x0F,0x0A) Service Status [C]',['../group__c__rtk__service__status.html',1,'']]],
  ['service_20status_20cpp_55',['(0x0F,0x0A) Service Status [CPP]',['../group__cpp__rtk__service__status.html',1,'']]],
  ['set_20idle_20c_56',['(0x01,0x02) Set Idle [C]',['../group__c__base__set__idle.html',1,'']]],
  ['set_20idle_20cpp_57',['(0x01,0x02) Set Idle [CPP]',['../group__cpp__base__set__idle.html',1,'']]],
  ['set_20initial_20attitude_20c_58',['(0x0D,0x02) Set Initial Attitude [C]',['../group__c__filter__set__initial__attitude.html',1,'']]],
  ['set_20initial_20attitude_20cpp_59',['(0x0D,0x02) Set Initial Attitude [CPP]',['../group__cpp__filter__set__initial__attitude.html',1,'']]],
  ['set_20initial_20heading_20c_60',['(0x0D,0x03) Set Initial Heading [C]',['../group__c__filter__set__initial__heading.html',1,'']]],
  ['set_20initial_20heading_20cpp_61',['(0x0D,0x03) Set Initial Heading [CPP]',['../group__cpp__filter__set__initial__heading.html',1,'']]],
  ['settings_20c_62',['settings c',['../group__c__3dm__constellation__settings.html',1,'(0x0C,0x21) Constellation Settings [C]'],['../group__c__3dm__gnss__sbas__settings.html',1,'(0x0C,0x22) Gnss Sbas Settings [C]'],['../group__c__3dm__device__settings.html',1,'(0x0C,0x30) Device Settings [C]']]],
  ['settings_20cpp_63',['settings cpp',['../group__cpp__3dm__constellation__settings.html',1,'(0x0C,0x21) Constellation Settings [CPP]'],['../group__cpp__3dm__gnss__sbas__settings.html',1,'(0x0C,0x22) Gnss Sbas Settings [CPP]'],['../group__cpp__3dm__device__settings.html',1,'(0x0C,0x30) Device Settings [CPP]']]],
  ['shared_20data_20c_64',['Shared Data [C]',['../group__shared__data__c.html',1,'']]],
  ['shared_20data_20cpp_65',['Shared Data [CPP]',['../group__shared__data__cpp.html',1,'']]],
  ['signal_20configuration_20c_66',['(0x0E,0x02) Signal Configuration [C]',['../group__c__gnss__signal__configuration.html',1,'']]],
  ['signal_20configuration_20cpp_67',['(0x0E,0x02) Signal Configuration [CPP]',['../group__cpp__gnss__signal__configuration.html',1,'']]],
  ['soft_20iron_20matrix_20c_68',['(0x0C,0x3B) Mag Soft Iron Matrix [C]',['../group__c__3dm__mag__soft__iron__matrix.html',1,'']]],
  ['soft_20iron_20matrix_20cpp_69',['(0x0C,0x3B) Mag Soft Iron Matrix [CPP]',['../group__cpp__3dm__mag__soft__iron__matrix.html',1,'']]],
  ['soft_20iron_20matrix_20noise_20c_70',['(0x0D,0x2C) Soft Iron Matrix Noise [C]',['../group__c__filter__soft__iron__matrix__noise.html',1,'']]],
  ['soft_20iron_20matrix_20noise_20cpp_71',['(0x0D,0x2C) Soft Iron Matrix Noise [CPP]',['../group__cpp__filter__soft__iron__matrix__noise.html',1,'']]],
  ['soft_20reset_20c_72',['(0x01,0x7E) Soft Reset [C]',['../group__c__base__soft__reset.html',1,'']]],
  ['soft_20reset_20cpp_73',['(0x01,0x7E) Soft Reset [CPP]',['../group__cpp__base__soft__reset.html',1,'']]],
  ['source_20c_74',['source c',['../group__c__3dm__pps__source.html',1,'(0x0C,0x28) Pps Source [C]'],['../group__c__filter__gnss__source.html',1,'(0x0D,0x15) Gnss Source [C]'],['../group__c__filter__heading__source.html',1,'(0x0D,0x18) Heading Source [C]'],['../group__c__filter__magnetic__declination__source.html',1,'(0x0D,0x43) Magnetic Declination Source [C]'],['../group__c__filter__inclination__source.html',1,'(0x0D,0x4C) Inclination Source [C]'],['../group__c__filter__mag__field__magnitude__source.html',1,'(0x0D,0x4D) Mag Field Magnitude Source [C]'],['../group__c__shared__event__source.html',1,'(0xFF,0xD0) Event Source [C]']]],
  ['source_20cpp_75',['source cpp',['../group__cpp__3dm__pps__source.html',1,'(0x0C,0x28) Pps Source [CPP]'],['../group__cpp__filter__gnss__source.html',1,'(0x0D,0x15) Gnss Source [CPP]'],['../group__cpp__filter__heading__source.html',1,'(0x0D,0x18) Heading Source [CPP]'],['../group__cpp__filter__magnetic__declination__source.html',1,'(0x0D,0x43) Magnetic Declination Source [CPP]'],['../group__cpp__filter__inclination__source.html',1,'(0x0D,0x4C) Inclination Source [CPP]'],['../group__cpp__filter__mag__field__magnitude__source.html',1,'(0x0D,0x4D) Mag Field Magnitude Source [CPP]'],['../group__cpp__shared__event__source.html',1,'(0xFF,0xD0) Event Source [CPP]']]],
  ['specific_20utilities_76',['Platform specific utilities',['../group__microstrain__platform.html',1,'']]],
  ['speed_20c_77',['(0x01,0x09) Comm Speed [C]',['../group__c__base__comm__speed.html',1,'']]],
  ['speed_20cpp_78',['(0x01,0x09) Comm Speed [CPP]',['../group__cpp__base__comm__speed.html',1,'']]],
  ['speed_20lever_20arm_20c_79',['(0x0D,0x61) Speed Lever Arm [C]',['../group__c__filter__speed__lever__arm.html',1,'']]],
  ['speed_20lever_20arm_20cpp_80',['(0x0D,0x61) Speed Lever Arm [CPP]',['../group__cpp__filter__speed__lever__arm.html',1,'']]],
  ['speed_20measurement_20c_81',['(0x0D,0x60) Speed Measurement [C]',['../group__c__filter__speed__measurement.html',1,'']]],
  ['speed_20measurement_20cpp_82',['(0x0D,0x60) Speed Measurement [CPP]',['../group__cpp__filter__speed__measurement.html',1,'']]],
  ['standard_20atmosphere_20c_83',['(0x82,0x20) Standard Atmosphere [C]',['../group__c__filter__standard__atmosphere.html',1,'']]],
  ['standard_20atmosphere_20cpp_84',['(0x82,0x20) Standard Atmosphere [CPP]',['../group__cpp__filter__standard__atmosphere.html',1,'']]],
  ['state_20c_85',['state c',['../group__c__3dm__gpio__state.html',1,'(0x0C,0x42) Gpio State [C]'],['../group__c__filter__heading__update__state.html',1,'(0x82,0x14) Heading Update State [C]'],['../group__c__system__gpio__state.html',1,'(0xA0,0x03) Gpio State [C]']]],
  ['state_20cpp_86',['state cpp',['../group__cpp__3dm__gpio__state.html',1,'(0x0C,0x42) Gpio State [CPP]'],['../group__cpp__filter__heading__update__state.html',1,'(0x82,0x14) Heading Update State [CPP]'],['../group__cpp__system__gpio__state.html',1,'(0xA0,0x03) Gpio State [CPP]']]],
  ['station_20info_20c_87',['(0x81,0x30) Base Station Info [C]',['../group__c__gnss__base__station__info.html',1,'']]],
  ['station_20info_20cpp_88',['(0x81,0x30) Base Station Info [CPP]',['../group__cpp__gnss__base__station__info.html',1,'']]],
  ['status_20c_89',['status c',['../group__c__3dm__get__event__trigger__status.html',1,'(0x0C,0x2C) Get Event Trigger Status [C]'],['../group__c__3dm__get__event__action__status.html',1,'(0x0C,0x2D) Get Event Action Status [C]'],['../group__c__rtk__service__status.html',1,'(0x0F,0x0A) Service Status [C]'],['../group__c__sensor__overrange__status.html',1,'(0x80,0x18) Overrange Status [C]'],['../group__c__gnss__hw__status.html',1,'(0x81,0x0D) Hw Status [C]'],['../group__c__gnss__satellite__status.html',1,'(0x81,0x20) Satellite Status [C]'],['../group__c__gnss__rtk__corrections__status.html',1,'(0x81,0x31) Rtk Corrections Status [C]'],['../group__c__filter__status.html',1,'(0x82,0x10) Status [C]'],['../group__c__filter__gnss__pos__aid__status.html',1,'(0x82,0x43) Gnss Pos Aid Status [C]'],['../group__c__filter__gnss__att__aid__status.html',1,'(0x82,0x44) Gnss Att Aid Status [C]'],['../group__c__filter__head__aid__status.html',1,'(0x82,0x45) Head Aid Status [C]'],['../group__c__filter__gnss__dual__antenna__status.html',1,'(0x82,0x49) Gnss Dual Antenna Status [C]'],['../group__c__system__time__sync__status.html',1,'(0xA0,0x02) Time Sync Status [C]']]],
  ['status_20cpp_90',['status cpp',['../group__cpp__3dm__get__event__trigger__status.html',1,'(0x0C,0x2C) Get Event Trigger Status [CPP]'],['../group__cpp__3dm__get__event__action__status.html',1,'(0x0C,0x2D) Get Event Action Status [CPP]'],['../group__cpp__rtk__service__status.html',1,'(0x0F,0x0A) Service Status [CPP]'],['../group__cpp__sensor__overrange__status.html',1,'(0x80,0x18) Overrange Status [CPP]'],['../group__cpp__gnss__hw__status.html',1,'(0x81,0x0D) Hw Status [CPP]'],['../group__cpp__gnss__satellite__status.html',1,'(0x81,0x20) Satellite Status [CPP]'],['../group__cpp__gnss__rtk__corrections__status.html',1,'(0x81,0x31) Rtk Corrections Status [CPP]'],['../group__cpp__filter__status.html',1,'(0x82,0x10) Status [CPP]'],['../group__cpp__filter__gnss__pos__aid__status.html',1,'(0x82,0x43) Gnss Pos Aid Status [CPP]'],['../group__cpp__filter__gnss__att__aid__status.html',1,'(0x82,0x44) Gnss Att Aid Status [CPP]'],['../group__cpp__filter__head__aid__status.html',1,'(0x82,0x45) Head Aid Status [CPP]'],['../group__cpp__filter__gnss__dual__antenna__status.html',1,'(0x82,0x49) Gnss Dual Antenna Status [CPP]'],['../group__cpp__system__time__sync__status.html',1,'(0xA0,0x02) Time Sync Status [CPP]']]],
  ['status_20flags_20c_91',['(0x0F,0x01) Get Status Flags [C]',['../group__c__rtk__get__status__flags.html',1,'']]],
  ['status_20flags_20cpp_92',['(0x0F,0x01) Get Status Flags [CPP]',['../group__cpp__rtk__get__status__flags.html',1,'']]],
  ['storage_20c_93',['(0x0F,0x20) Prod Erase Storage [C]',['../group__c__rtk__prod__erase__storage.html',1,'']]],
  ['storage_20cpp_94',['(0x0F,0x20) Prod Erase Storage [CPP]',['../group__cpp__rtk__prod__erase__storage.html',1,'']]],
  ['streaming_20c_95',['(0x0C,0x10) Factory Streaming [C]',['../group__c__3dm__factory__streaming.html',1,'']]],
  ['streaming_20cpp_96',['(0x0C,0x10) Factory Streaming [CPP]',['../group__cpp__3dm__factory__streaming.html',1,'']]],
  ['summary_20c_97',['(0x82,0x46) Aiding Measurement Summary [C]',['../group__c__filter__aiding__measurement__summary.html',1,'']]],
  ['summary_20cpp_98',['(0x82,0x46) Aiding Measurement Summary [CPP]',['../group__cpp__filter__aiding__measurement__summary.html',1,'']]],
  ['support_20c_99',['(0x0C,0x2A) Get Event Support [C]',['../group__c__3dm__get__event__support.html',1,'']]],
  ['support_20cpp_100',['(0x0C,0x2A) Get Event Support [CPP]',['../group__cpp__3dm__get__event__support.html',1,'']]],
  ['sv_20info_20c_101',['(0x81,0x0C) Sv Info [C]',['../group__c__gnss__sv__info.html',1,'']]],
  ['sv_20info_20cpp_102',['(0x81,0x0C) Sv Info [CPP]',['../group__cpp__gnss__sv__info.html',1,'']]],
  ['sync_20status_20c_103',['(0xA0,0x02) Time Sync Status [C]',['../group__c__system__time__sync__status.html',1,'']]],
  ['sync_20status_20cpp_104',['(0xA0,0x02) Time Sync Status [CPP]',['../group__cpp__system__time__sync__status.html',1,'']]],
  ['system_20commands_20c_105',['System Commands [C]',['../group__system__commands__c.html',1,'']]],
  ['system_20commands_20cpp_106',['System Commands [CPP]',['../group__system__commands__cpp.html',1,'']]],
  ['system_20data_20c_107',['System Data [C]',['../group__system__data__c.html',1,'']]],
  ['system_20data_20cpp_108',['System Data [CPP]',['../group__system__data__cpp.html',1,'']]]
];
