var searchData=
[
  ['uart_20baudrate_20c_0',['(0x0C,0x40) Uart Baudrate [C]',['../group__c__3dm__uart__baudrate.html',1,'']]],
  ['uart_20baudrate_20cpp_1',['(0x0C,0x40) Uart Baudrate [CPP]',['../group__cpp__3dm__uart__baudrate.html',1,'']]],
  ['uncertainty_20c_2',['uncertainty c',['../group__c__filter__position__llh__uncertainty.html',1,'(0x82,0x08) Position Llh Uncertainty [C]'],['../group__c__filter__velocity__ned__uncertainty.html',1,'(0x82,0x09) Velocity Ned Uncertainty [C]'],['../group__c__filter__euler__angles__uncertainty.html',1,'(0x82,0x0A) Euler Angles Uncertainty [C]'],['../group__c__filter__gyro__bias__uncertainty.html',1,'(0x82,0x0B) Gyro Bias Uncertainty [C]'],['../group__c__filter__accel__bias__uncertainty.html',1,'(0x82,0x0C) Accel Bias Uncertainty [C]'],['../group__c__filter__quaternion__attitude__uncertainty.html',1,'(0x82,0x12) Quaternion Attitude Uncertainty [C]'],['../group__c__filter__gyro__scale__factor__uncertainty.html',1,'(0x82,0x18) Gyro Scale Factor Uncertainty [C]'],['../group__c__filter__accel__scale__factor__uncertainty.html',1,'(0x82,0x19) Accel Scale Factor Uncertainty [C]'],['../group__c__filter__mag__bias__uncertainty.html',1,'(0x82,0x1B) Mag Bias Uncertainty [C]'],['../group__c__filter__magnetometer__offset__uncertainty.html',1,'(0x82,0x28) Magnetometer Offset Uncertainty [C]'],['../group__c__filter__magnetometer__matrix__uncertainty.html',1,'(0x82,0x29) Magnetometer Matrix Uncertainty [C]'],['../group__c__filter__antenna__offset__correction__uncertainty.html',1,'(0x82,0x31) Antenna Offset Correction Uncertainty [C]'],['../group__c__filter__clock__correction__uncertainty.html',1,'(0x82,0x33) Clock Correction Uncertainty [C]'],['../group__c__filter__multi__antenna__offset__correction__uncertainty.html',1,'(0x82,0x35) Multi Antenna Offset Correction Uncertainty [C]'],['../group__c__filter__ecef__pos__uncertainty.html',1,'(0x82,0x36) Ecef Pos Uncertainty [C]'],['../group__c__filter__ecef__vel__uncertainty.html',1,'(0x82,0x37) Ecef Vel Uncertainty [C]'],['../group__c__filter__odometer__scale__factor__error__uncertainty.html',1,'(0x82,0x48) Odometer Scale Factor Error Uncertainty [C]'],['../group__c__filter__aiding__frame__config__error__uncertainty.html',1,'(0x82,0x51) Aiding Frame Config Error Uncertainty [C]']]],
  ['uncertainty_20cpp_3',['uncertainty cpp',['../group__cpp__filter__position__llh__uncertainty.html',1,'(0x82,0x08) Position Llh Uncertainty [CPP]'],['../group__cpp__filter__velocity__ned__uncertainty.html',1,'(0x82,0x09) Velocity Ned Uncertainty [CPP]'],['../group__cpp__filter__euler__angles__uncertainty.html',1,'(0x82,0x0A) Euler Angles Uncertainty [CPP]'],['../group__cpp__filter__gyro__bias__uncertainty.html',1,'(0x82,0x0B) Gyro Bias Uncertainty [CPP]'],['../group__cpp__filter__accel__bias__uncertainty.html',1,'(0x82,0x0C) Accel Bias Uncertainty [CPP]'],['../group__cpp__filter__quaternion__attitude__uncertainty.html',1,'(0x82,0x12) Quaternion Attitude Uncertainty [CPP]'],['../group__cpp__filter__gyro__scale__factor__uncertainty.html',1,'(0x82,0x18) Gyro Scale Factor Uncertainty [CPP]'],['../group__cpp__filter__accel__scale__factor__uncertainty.html',1,'(0x82,0x19) Accel Scale Factor Uncertainty [CPP]'],['../group__cpp__filter__mag__bias__uncertainty.html',1,'(0x82,0x1B) Mag Bias Uncertainty [CPP]'],['../group__cpp__filter__magnetometer__offset__uncertainty.html',1,'(0x82,0x28) Magnetometer Offset Uncertainty [CPP]'],['../group__cpp__filter__magnetometer__matrix__uncertainty.html',1,'(0x82,0x29) Magnetometer Matrix Uncertainty [CPP]'],['../group__cpp__filter__antenna__offset__correction__uncertainty.html',1,'(0x82,0x31) Antenna Offset Correction Uncertainty [CPP]'],['../group__cpp__filter__clock__correction__uncertainty.html',1,'(0x82,0x33) Clock Correction Uncertainty [CPP]'],['../group__cpp__filter__multi__antenna__offset__correction__uncertainty.html',1,'(0x82,0x35) Multi Antenna Offset Correction Uncertainty [CPP]'],['../group__cpp__filter__ecef__pos__uncertainty.html',1,'(0x82,0x36) Ecef Pos Uncertainty [CPP]'],['../group__cpp__filter__ecef__vel__uncertainty.html',1,'(0x82,0x37) Ecef Vel Uncertainty [CPP]'],['../group__cpp__filter__odometer__scale__factor__error__uncertainty.html',1,'(0x82,0x48) Odometer Scale Factor Error Uncertainty [CPP]'],['../group__cpp__filter__aiding__frame__config__error__uncertainty.html',1,'(0x82,0x51) Aiding Frame Config Error Uncertainty [CPP]']]],
  ['up_20vector_20c_4',['(0x80,0x11) Up Vector [C]',['../group__c__sensor__up__vector.html',1,'']]],
  ['up_20vector_20cpp_5',['(0x80,0x11) Up Vector [CPP]',['../group__cpp__sensor__up__vector.html',1,'']]],
  ['update_20c_6',['update c',['../group__c__base__gps__time__update.html',1,'(0x01,0x72) Gps Time Update [C]'],['../group__c__filter__external__gnss__update.html',1,'(0x0D,0x16) External Gnss Update [C]'],['../group__c__filter__external__heading__update.html',1,'(0x0D,0x17) External Heading Update [C]']]],
  ['update_20cpp_7',['update cpp',['../group__cpp__base__gps__time__update.html',1,'(0x01,0x72) Gps Time Update [CPP]'],['../group__cpp__filter__external__gnss__update.html',1,'(0x0D,0x16) External Gnss Update [CPP]'],['../group__cpp__filter__external__heading__update.html',1,'(0x0D,0x17) External Heading Update [CPP]']]],
  ['update_20matrix_20c_8',['(0x80,0x0B) Comp Orientation Update Matrix [C]',['../group__c__sensor__comp__orientation__update__matrix.html',1,'']]],
  ['update_20matrix_20cpp_9',['(0x80,0x0B) Comp Orientation Update Matrix [CPP]',['../group__cpp__sensor__comp__orientation__update__matrix.html',1,'']]],
  ['update_20state_20c_10',['(0x82,0x14) Heading Update State [C]',['../group__c__filter__heading__update__state.html',1,'']]],
  ['update_20state_20cpp_11',['(0x82,0x14) Heading Update State [CPP]',['../group__cpp__filter__heading__update__state.html',1,'']]],
  ['update_20with_20time_20c_12',['(0x0D,0x1F) External Heading Update With Time [C]',['../group__c__filter__external__heading__update__with__time.html',1,'']]],
  ['update_20with_20time_20cpp_13',['(0x0D,0x1F) External Heading Update With Time [CPP]',['../group__cpp__filter__external__heading__update__with__time.html',1,'']]],
  ['utc_20time_20c_14',['(0x81,0x08) Utc Time [C]',['../group__c__gnss__utc__time.html',1,'']]],
  ['utc_20time_20cpp_15',['(0x81,0x08) Utc Time [CPP]',['../group__cpp__gnss__utc__time.html',1,'']]],
  ['utilities_16',['utilities',['../group__mip__extras.html',1,'Extra utilities'],['../group__mip__platform.html',1,'Platform specific utilities']]]
];
